### ISSUE TITLE
auto sync no longer syncing

### ISSUE THREAD

**Issue by jough74** [jaredcobb/ccb-core#19]
Running v 1.0.6 on wordpress 4.9.8.   Auto sync no longer syncs. Manual syncs complete successfully however.

**Comment by nicholaspetersen** [comment]
Same issue. Any ideas why this is no longer working?

**Comment by jaredcobb** [comment]
@jough74 @nicholaspetersen There was a change to how the WordPress cron system makes certain core functions available. One of the missing functions had to do with image downloads (specifically if you are synchronizing group images in the background).

I released a fix this evening so you should be able to update to 1.0.7 to get the fix. This update also includes some performance improvements and compatibility fixes for newer versions of PHP (specifically PHP 7.2 and above).

After the upgrade, if any of you have issues with the auto sync please feel free to let me know here again and I can try to take a closer look. But I’m fairly certain this was the issue because I was able to replicate it.

**Comment by tamala73** [comment]
i am still having issues after upgrading to 1.0.7
