### ISSUE TITLE
php 7.2 compatibility?

### ISSUE THREAD

**Issue by jough74** [jaredcobb/ccb-core#21]
Will this plugin be updated to work with php 7.2 in the near future?  I understand php7.0 will soon not be supported. My compatibility checking plugin says this plugin is not currently 7.2 (or 7.1) compatible.Thanks

**Comment by jaredcobb** [comment]
@jough74 This evening I released version 1.0.7 https://github.com/jaredcobb/ccb-core/releases/tag/1.0.7 and the update should also be available in your dashboard.

The compatibility plugin may still flag an incompatibility issue because I'm still including an encryption library for sites running PHP 5.6 / PHP 7.0. However if your site is running PHP 7.2 or above it will not load the incompatible library (and instead will use the native encryption methods that are available).
